name: SaluteRemotePlus
options:
  bundleIdPrefix: com.andrey
  deploymentTarget:
    iOS: "15.0"
targets:
  SaluteRemotePlus:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: SaluteRemotePlus/Sources
    info:
      path: SaluteRemotePlus/Resources/Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.andrey.saluteremoteplus
      PRODUCT_NAME: SaluteRemotePlus
      SWIFT_VERSION: "5.0"
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGN_IDENTITY: ""
      TARGETED_DEVICE_FAMILY: "1"
      ENABLE_BITCODE: NO
    dependencies:
      - package: JazzSDK
packages:
  JazzSDK:
    url: https://github.com/salute-developers/jazz-ios-sdk.git
    revision: 6d5f92869690fa22bb489a9089aa554d733c6936
